NAME= hashtest
TYPE= APP
SRCS= test.cpp
#SRCS= hashtest.cpp BDictionary.cpp
RSRCS= 
LIBS= be stdc++
LIBPATHS= 
SYSTEM_INCLUDE_PATHS = 
LOCAL_INCLUDE_PATHS = 
OPTIMIZE= 
DEFINES= 
WARNINGS = ALL
SYMBOLS = 
DEBUGGER = 
COMPILER_FLAGS =
LINKER_FLAGS =
include /boot/develop/etc/makefile-engine
