NAME= qstring_test
TYPE= APP
SRCS= qstring_test.cpp
RSRCS= 
LIBS= be WebCore
LIBPATHS= 
SYSTEM_INCLUDE_PATHS = 
LOCAL_INCLUDE_PATHS = 
OPTIMIZE= 
DEFINES= 
WARNINGS = ALL
SYMBOLS = 
DEBUGGER = 
COMPILER_FLAGS =
LINKER_FLAGS =
include /boot/develop/etc/makefile-engine

